[package]
name = "double-trait"
version = "0.1.0"
edition = "2024"

[dependencies]
double-derive = { path = "../double-derive" }

[dev-dependencies]
tokio = { version = "1.45.1", features = ["rt", "macros"] }
